### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amankumarrr**
Adding current usage information as requested by @tiagov8.

image

**Figure: Updated README.md**

### CODE REVIEW

**Comment by tiagov8** [comment]
Hey @amankumarrr 

- [ ] 1. See my comment https://github.com/SSWConsulting/SSW.MegaMenu/commit/ffbc32a71af8ca331a7410e5cc8c3536152cdfb8#commitcomment-143011071
- [ ] 2. Ping me on Teams again after talking to the team

**Review by tiagov8 — APPROVED** [review]
As per our conversation, approved but I feel that info could be on the Wiki tab

**Comment by jeoffreyfischer** [comment]
As per my conversation with @wicksipedia, we need:
- a README for Dev - so how to update the code
- a Wiki page for non-Dev - so how to update the features using Tina

**Review by jeoffreyfischer — APPROVED** [review]
LGTM

**Pull request merged**
